CREATE TABLE IF NOT EXISTS store (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image BLOB
);

CREATE TABLE IF NOT EXISTS camera1 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_capture INTEGER DEFAULT 0
);

INSERT OR IGNORE INTO store (id, image) VALUES (1, '');
INSERT OR IGNORE INTO store (id, image) VALUES (2, '');

INSERT OR IGNORE INTO camera1 (id, image_capture) VALUES (1,0);